In [1]:
#import dependencies
import pandas as pd
import requests
import gmaps
from config import g_key

In [2]:
file_to_load = "weather_data/weatherpy_challenge.csv"

city_data_df = pd.read_csv(file_to_load)

In [3]:
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Aklavik,CA,2019-11-08 19:12:13,68.22,-135.01,10.40,78,90,1.97,light snow,0.00,0.00
1,1,Mar Del Plata,AR,2019-11-08 19:12:13,-46.43,-67.52,53.20,43,0,16.51,clear sky,0.00,0.00
2,2,Punta Arenas,CL,2019-11-08 19:12:14,-53.16,-70.91,48.20,49,40,26.40,scattered clouds,0.00,0.00
3,3,Ahipara,NZ,2019-11-08 19:12:14,-35.17,173.16,64.99,100,49,13.31,scattered clouds,0.00,0.00
4,4,Mikkeli,FI,2019-11-08 19:12:14,61.69,27.27,28.40,100,90,5.82,light shower snow,0.00,0.00
5,5,Busselton,AU,2019-11-08 19:09:48,-33.64,115.35,63.00,39,0,16.64,clear sky,0.00,0.00
6,6,Agadez,NE,2019-11-08 19:12:14,16.97,7.99,86.00,20,0,9.17,clear sky,0.00,0.00
7,7,Yenagoa,NG,2019-11-08 19:10:47,4.92,6.26,78.98,89,87,4.18,moderate rain,3.19,0.00
8,8,Geraldton,CA,2019-11-08 19:11:05,49.72,-86.95,17.60,57,90,13.87,light snow,0.00,0.00
9,9,Teguldet,RU,2019-11-08 19:10:50,57.31,88.17,34.54,97,100,9.35,light snow,0.00,1.13

In [4]:
#user input
min_temp = float(input("What is your minimum temperature preference?"))
max_temp = float(input("What is your maximum temperature preference?"))
rain_pref = str(input("Do you want it to be raining? (yes/no)"))
snow_pref = str(input("Do you want it to be snowing? (yes/no)"))

yes = ['y', 'yes', 'ys']
no = ['n', 'no', 'noo']

What is your minimum temperature preference?0
What is your maximum temperature preference?120
Do you want it to be raining? (yes/no)yes
Do you want it to be snowing? (yes/no)no

In [5]:
#conditions for preferred cities

if rain_pref in yes:
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                            (city_data_df["Max Temp"] >= min_temp) & \
                                            (city_data_df["Rain inches (last 3 hrs)"] > 0)]                                            
elif snow_pref in yes:
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                           (city_data_df["Max Temp"] >= min_temp) & \
                                           (city_data_df["Snow inches (last 3 hrs)"] > 0)]
else:
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                        (city_data_df["Max Temp"] >= min_temp) & \
                                        (city_data_df["Rain inches (last 3 hrs)"] == 0) & \
                                        (city_data_df["Snow inches (last 3 hrs)"] == 0)]

preferred_cities_df.count()

City_ID                     46
City                        46
Country                     46
Date                        46
Lat                         46
Lng                         46
Max Temp                    46
Humidity                    46
Cloudiness                  46
Wind Speed                  46
Current Description         46
Rain inches (last 3 hrs)    46
Snow inches (last 3 hrs)    46
dtype: int64

In [7]:
#creating hotel_df 
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
7,Yenagoa,NG,78.98,moderate rain,4.92,6.26,
11,Mataura,NZ,54.00,light rain,-46.19,168.86,
12,Waingapu,ID,82.02,light rain,-9.65,120.26,
13,Faanui,PF,81.25,light rain,-16.48,-151.75,
23,Morondava,MG,78.22,light rain,-20.30,44.28,
33,Telimele,GN,78.03,light rain,10.90,-13.03,
44,Aripuana,BR,96.64,light rain,-9.17,-60.63,
46,Kaitangata,NZ,57.00,light rain,-46.28,169.85,
73,Sorong,ID,72.55,light rain,-0.86,131.25,
77,Kasongo-Lunda,CD,70.72,light rain,-6.48,16.82,

In [8]:
#creating parameters for google hotel search
gmaps.configure(api_key=g_key)
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

In [9]:
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"
    g_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(g_url, params=params).json()
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
#save
file_to_save = "weather_data/weatherpy_vacation.csv"
hotel_df.to_csv(file_to_save, index_label="City_ID")

hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
7,Yenagoa,NG,78.98,moderate rain,4.92,6.26,Amba Hotels Limited
11,Mataura,NZ,54.00,light rain,-46.19,168.86,Ellie's Villa
12,Waingapu,ID,82.02,light rain,-9.65,120.26,Pondok Wisata Elim
13,Faanui,PF,81.25,light rain,-16.48,-151.75,Bora-Bora Pearl Beach Resort & Spa
23,Morondava,MG,78.22,light rain,-20.30,44.28,La Case Bambou

In [11]:
#info_box_template
#template for information box
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store hotel names.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [12]:
# Add a map with markers of vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,\
             max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)

fig.add_layer(marker_layer)
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))